# Generated by Django 4.1.7 on 2025-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_barangay_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='complaint',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
