# Generated by Django 4.1.7 on 2025-01-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaint',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
