# Generated by Django 4.1.7 on 2025-01-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='complaint',
        ),
    ]
