# Generated by Django 4.1.7 on 2025-01-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='complaint',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
