# Generated by Django 4.1.7 on 2025-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaint',
            field=models.TextField(blank=True, choices=[('general_illness', 'General Illness'), ('injury', 'Injury'), ('checkup', 'Check-up'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
