# Generated by Django 4.1.7 on 2025-01-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(max_length=200)),
                ('assessment', models.TextField(default='No assessment provided yet', max_length=200)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryStorageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('Regular', 'Regular'), ('Priority', 'Priority Lane (PWD/Pregnant)')], default='Regular', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Being Assessed', 'Being Assessed'), ('Queued for Treatment', 'Queued for Treatment'), ('Completed', 'Completed')], default='Waiting', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'unique_together': {('patient',)},
            },
        ),
    ]
