# Generated by Django 4.1.7 on 2025-01-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporarystoragequeue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporarystoragequeue', to='patient.patient'),
        ),
    ]
