# Generated by Django 4.1.7 on 2025-01-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporarystoragequeue', to='patient.patient'),
        ),
    ]
