# Generated by Django 4.1.7 on 2025-01-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0003_alter_temporarystoragequeue_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporarystoragequeue',
            unique_together=set(),
        ),
    ]
