# Generated by Django 4.1.7 on 2025-01-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0002_alter_temporarystoragequeue_unique_together_and_more'),
        ('queueing', '0004_alter_temporarystoragequeue_unique_together'),
    ]

    operations = [
    ]
