# Generated by Django 5.1.4 on 2024-12-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
