# Generated by Django 4.1.7 on 2024-12-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_patient_id_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStorageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
            options={
                'unique_together': {('patient',)},
            },
        ),
    ]
