# Generated by Django 4.1.7 on 2025-01-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_temporarystoragequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('BeingAssessed', 'Being Assessed'), ('Completed', 'Completed')], default='Waiting', max_length=50),
        ),
        migrations.CreateModel(
            name='PreliminaryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
    ]
