# Generated by Django 4.1.7 on 2025-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_temporarystoragequeue_status_preliminaryassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryassessment',
            name='assessment',
            field=models.TextField(default='No assessment provided yet', max_length=200),
        ),
        migrations.AlterField(
            model_name='preliminaryassessment',
            name='symptoms',
            field=models.TextField(max_length=200),
        ),
    ]
