# Generated by Django 4.1.7 on 2025-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_preliminaryassessment_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Being Assessed', 'Being Assessed'), ('Queued for Treatment', 'Queued for Treatment'), ('Completed', 'Completed')], default='Waiting', max_length=50),
        ),
    ]
