# Generated by Django 4.1.7 on 2025-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_temporarystoragequeue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarystoragequeue',
            name='priority',
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='priority_level',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Priority', 'Priority Lane (PWD/Pregnant)')], default='Regular', max_length=10),
        ),
    ]
