# Generated by Django 4.1.7 on 2025-01-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('appointments', '0009_remove_temporarystoragequeue_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliminaryassessment',
            name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='temporarystoragequeue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='temporarystoragequeue',
            name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PreliminaryAssessment',
        ),
        migrations.DeleteModel(
            name='TemporaryStorageQueue',
        ),
    ]
